app_name = "web-admin-angular-tractor-tuesday" # should be base folder name 
existing_repo_url = "https://github.com/manku211/react-vite-app"
ssm_github_access_token_name = ""
branch_name = "main"
framework = "React" # should be reactjs,angularjs and nextjs
enable_environment_variables = false
aws_access_key = ""
aws_secret_key = ""
region = "us-east-1"
build = ""
app_id = ""
