project_name            = "test-project"
environment         =  "dev"
aws_access_key             = ""     #use export  aws_access_key
aws_secret_key             = ""     # use export aws_secret_key 
region                     = "us-east-1"
cidr_block =  "10.6.0.0/16" # req.
enable_nat_gateway = true
az_count = 2
vpc_id  = "vpc-093500b885bd9d886"
create_ec2 = true
